<?php

namespace TF\ApiBundle\Repository;

/**
 * tab_countryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tab_countryRepository extends \Doctrine\ORM\EntityRepository
{
}
