<?php

namespace TF\ApiBundle\Repository;

/**
 * tab_header_docRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tab_header_docRepository extends \Doctrine\ORM\EntityRepository
{
}
