<?php

namespace TF\ApiBundle\Repository;

/**
 * tab_line_docRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tab_line_docRepository extends \Doctrine\ORM\EntityRepository
{
}
